### ISSUE TITLE
Pro: exception encountered during stable cursor production for ActiveRecord::Relation

### ISSUE THREAD

**Issue by steobrien** [rmosolgo/graphql-ruby#1266]
We have a relation with a fairly complex order, along the lines of the following:

```ruby
order_statement = <<~SQL
  high_priority DESC,
  CASE
    WHEN (
      important = FALSE AND
        (
          activity_at > '#{window.start.utc}' AND
          activity_at < '#{window.end.utc}'
        )
      )
    THEN 0
    ELSE 1
  END,
  created_at ASC
SQL

relation = Model.order(order_statement)
```

This seems to produce a query like
```SQL
SELECT  models.*, models.high_priority AS cursor_0, models.CASE AS cursor_1, models.created_at AS cursor_2, models.id AS cursor_3…
```

Which crashes, as of course there's no column `CASE`.

When I monkey patch the pro gem’s `Order.normalize`, to skip over the problematic sort, it appears to me like everything works fine.

Can the gem support this use case?

**Comment by rmosolgo** [comment]
Yes, I think it should be straightforward addition! Thanks for the great bug report. I've just released 1.6.4 (9f6c9f62) that should support this, can you give that version a try?

**Comment by steobrien** [comment]
Great! Seems to have fixed the problem.

**Comment by steobrien** [comment]
My mistake – I must have needed to restart the server or something, I'm still seeing the problem after all.

I still see:
```
 ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column models.case does not exist
```

From a quick `binding.pry` into `Order.normalize`, it seems your new regex (`/^\s*(case.*end)\s*(asc|desc)?\s*$/i`) is not matching because we have just one `order_value` with internal commas, and therefore `v` is equal to `"high_priority DESC, CASE WHEN…"`.

Perhaps this SQL string needs to be preprocessed?

**Comment by rmosolgo** [comment]
Derp, I missed the commas! 

The thing is, I'm not sure we can support that with out full-on parsing the SQL. (we couldn't just split on `,`, since it may also be present in a function call)

The alternative is to attach the order clauses one at a time, for example: 

```ruby 
relation = Model 
  .order("high_priority DESC")
  .order(case_stmt)
  .order("created_at ASC")
```

Would that work in your application?

**Comment by steobrien** [comment]
Thanks! That's a good idea and works nicely for us.
