### ISSUE TITLE
Unexpected behavior when combining prepare block with complexity block

### ISSUE THREAD

**Issue by drewmbrien** [rmosolgo/graphql-ruby#1641]
Just checking whether or not this behavior is expected (excuse the contrived example).

if I define the following in `query_type.rb`, everything works as expected:

```
field :foo do
    type types.String
    argument :bar, types.String, prepare: ->(bar, _ctx) do
      return GraphQL::ExecutionError.new('baz is illegal') if bar == 'baz'
      bar
    end
    complexity 1
    resolve ->(_obj, args, _ctx) { 'biz' }
end
```

```
# happy path request
{
  foo(bar: "boz")
}

# happy path response
{
  "data": {
    "foo": "biz"
  }
}
```

```
# error path request
{
  foo(bar: "baz")
}

# error path response
{
  "data": {
    "foo": null
  },
  "errors": [
    {
      "message": "baz is illegal",
      "locations": [
        {
          "line": 27,
          "column": 7
        }
      ],
      "path": [
        "foo"
      ]
    }
  ]
}
```

However, if I try to update `foo` to use a complexity block (instead of the hard-coded integer) it seems like the `GraphQL::ExecutionError` gets raised when I call `AppSchema.execute(...)` in my controller.  It results in unexpected responses when the rule in the `prepare` block is broken.

```
field :foo do
    type types.String
    argument :bar, types.String, prepare: ->(bar, _ctx) do
      return GraphQL::ExecutionError.new('baz is illegal') if bar == 'baz'
      bar
    end
    complexity ->(_ctx, _args, child_complexity) { child_complexity }
    resolve ->(_obj, args, _ctx) { 'biz' }
end
```

```
# error path request
{
  foo(bar: "baz")
}
```

```
# error path response
{
  "data": null,
  "errors": [
    {
      "message": "I couldn't communicate with the GraphQL server at the provided URL. Is it correct?"
    }
  ]
}
```

```
# error path rails log output
[#17902] FATAL -- : GraphQL::ExecutionError (baz is illegal):
[#17902] FATAL -- :   app/controllers/api/v2/graphql_controller.rb:13:in `execute'
...
```

We're currently using version 1.7.14

**Comment by rmosolgo** [comment]
I think this was probably fixed by https://github.com/rmosolgo/graphql-ruby/pull/1602 which was released in 1.8.4, could you update to that version and see how it goes?

**Comment by drewmbrien** [comment]
Thanks for the quick response!

I just updated to 1.8.4 and I'm still seeing the issue.

Additional info: this only seems to be an issue when `max_complexity` is set (this is true for both 1.7.14 and 1.8.4).

**Comment by rmosolgo** [comment]
Thanks for giving it a try, could you share the full stack trace on the latest graphql-ruby version?

**Comment by drewmbrien** [comment]
of course

```
GraphQL::ExecutionError: baz is illegal
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/query/literal_input.rb" line 85 in block in from_arguments
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/query/literal_input.rb" line 64 in each
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/query/literal_input.rb" line 64 in from_arguments
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/query/arguments_cache.rb" line 14 in block (2 levels) in build
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/query.rb" line 218 in arguments_for
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/internal_representation/node.rb" line 110 in arguments
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/query_complexity.rb" line 60 in get_complexity
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/query_complexity.rb" line 37 in call
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/reducer_state.rb" line 15 in call
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 72 in block in visit_analyzers
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 71 in each
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 71 in visit_analyzers
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 67 in reduce_node
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 63 in block (2 levels) in reduce_node
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 62 in each
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 62 in block in reduce_node
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 61 in each
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 61 in reduce_node
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 46 in block (2 levels) in analyze_query
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 45 in each
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 45 in block in analyze_query
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in block in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 71 in call_tracers
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 40 in analyze_query
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 12 in block (2 levels) in analyze_multiplex
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 10 in map
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 10 in block in analyze_multiplex
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in block in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 71 in call_tracers
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/analysis/analyze_query.rb" line 8 in analyze_multiplex
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/multiplex.rb" line 173 in block in instrument_and_analyze
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 29 in block (2 levels) in apply_instrumenters
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 46 in block (2 levels) in each_query_call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 41 in each_query_call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 45 in block in each_query_call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 58 in call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 44 in each_query_call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 27 in block in apply_instrumenters
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 58 in call_hooks
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/instrumentation.rb" line 26 in apply_instrumenters
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/multiplex.rb" line 166 in instrument_and_analyze
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/multiplex.rb" line 68 in block in run_queries
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in block in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 71 in call_tracers
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/tracing.rb" line 57 in trace
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/multiplex.rb" line 58 in run_queries
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/execution/multiplex.rb" line 48 in run_all
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/schema.rb" line 341 in block in multiplex
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/schema.rb" line 1048 in with_definition_error_check
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/schema.rb" line 340 in multiplex
File "~/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/graphql-1.8.4/lib/graphql/schema.rb" line 317 in execute
File "~/project_root/app/controllers/api/v2/graphql_controller.rb", line 14 in execute
```
