### ISSUE TITLE
1.8.9 breaks graphql-batch compatibility

### ISSUE THREAD

**Issue by Mange** [rmosolgo/graphql-ruby#1867]
I suspect the error comes from #1784.

When using a `Promise` from graphql-batch in 1.8.9 and later, this error is raise:

```
  no block given (yield)
    /home/mange/.rvm/gems/ruby-2.4.4@hemnet-ng/gems/graphql-1.8.10/lib/graphql/schema.rb:1022:in `sync_lazy'
    /home/mange/.rvm/gems/ruby-2.4.4@hemnet-ng/gems/graphql-1.8.10/lib/graphql/field.rb :326:in `call'
    /home/mange/.rvm/gems/ruby-2.4.4@hemnet-ng/gems/graphql-1.8.10/lib/graphql/field.rb:302:in `lazy_resolve'
    /home/mange/.rvm/gems/ruby-2.4.4@hemnet-ng/gems/graphql-1.8.10/lib/graphql/execution/execute.rb:122:in `block (2 levels) in resolve_field'
    /home/mange/.rvm/gems/ruby-2.4.4@hemnet-ng/gems/graphql-1.8.10/lib/graphql/tracing.rb:62:in `block in trace'
```

Going back to 1.8.8 fixes the error and promises resolve naturally. Is there something that needs to be done to get this working on the latest version?

A hint: Promises still work using the old `.define` DSL. We encountered this after upgrading to 1.8.10 and then started to rewrite the schema using the new class-based definitions. Before changing the schema, this error did not appear.

Our schema:

```ruby
module FooAPI
  class Schema < GraphQL::Schema
    query QueryRoot

    orphan_types […]

    max_depth 20

    use GraphQL::Batch
    use GraphQL::Backtrace

    instrument :query, FooInstrumentation.new

    middleware(GraphQL::Schema::TimeoutMiddleware.new(max_seconds: 2))

    def self.resolve_type(_type, object, _context)
      ResolveGraphQLType.call(schema: Schema, object: object)
    end
  end
end
```

**Comment by rmosolgo** [comment]
Ick, I saw bug related to this too. I'll try to clean it up soon, I'm not quite sure what the fix will be.

**Comment by rmosolgo** [comment]
I looked for this issue and found something that I _think_ was the same, although the error message was different. I released a change in 1.8.15 that should do the job, but please reopen this issue with the new error message & backtrace if you encounter the same issue on that version!

**Comment by Mange** [comment]
Thank you. I'll try it out during the week!

**Comment by teoljungberg** [comment]
I upgrade from 1.8.8 to 1.8.15 and the issue still stands sadly, the application is on the latest and greatest version of graphql-batch as well.

Provided is the new backtrace, I've excluded RSpec from the backtrace.

```
=> ["/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/backtrace/tracer.rb:37:in `rescue in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/backtrace/tracer.rb:30:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:58:in `run_queries'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:168:in `block in result'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:357:in `with_prepared_ast'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:167:in `result'",
 "/Users/teo/src/universalavenue/UniversalAvenue/spec/graphql/offer_orders/offer_order_mutations_spec.rb:54:in `block (3 levels) in <top (required)>'",
# ...
]
```

And of `#cause.backtrace`:

```
=> ["/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/schema.rb:1068:in `sync_lazy'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/field.rb:326:in `call'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-pro-1.9.9/lib/graphql/pro/access/instrumentation/authorized_resolve.rb:24:in `call'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/field.rb:302:in `lazy_resolve'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:122:in `block (2 levels) in resolve_field'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/platform_tracing.rb:34:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/backtrace/tracer.rb:45:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:119:in `block in resolve_field'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy.rb:34:in `value'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:40:in `block (2 levels) in resolve_in_place'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:39:in `each'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:39:in `each_with_index'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:39:in `block in resolve_in_place'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy.rb:34:in `value'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:81:in `deep_sync'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy/resolve.rb:29:in `resolve'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/lazy.rb:19:in `resolve'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:81:in `block in resolve_selection'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:64:in `each'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:64:in `resolve_selection'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/newrelic_rpm-5.4.0.347/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/backtrace/tracer.rb:45:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/execute.rb:32:in `resolve_root_selection'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:108:in `begin_query'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:80:in `map'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:175:in `block in instrument_and_analyze'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:167:in `instrument_and_analyze'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/newrelic_rpm-5.4.0.347/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `block in call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/backtrace/tracer.rb:30:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:73:in `call_tracers'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/execution/multiplex.rb:58:in `run_queries'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:168:in `block in result'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:357:in `with_prepared_ast'",
 "/Users/teo/src/universalavenue/UniversalAvenue/.bundle/vendor/gems/graphql-1.8.15/lib/graphql/query.rb:167:in `result'",
 "/Users/teo/src/universalavenue/UniversalAvenue/spec/graphql/offer_orders/offer_order_mutations_spec.rb:54:in `block (3 levels) in <top (required)>'",
 # ...
]
```

**Comment by rmosolgo** [comment]
Oops 😖 ! Thanks for sharing that updated stack trace, that was really helpful. I tried again in #2112 and release 1.8.16 with the changes. Could you give that version a try and let me know what you find??

**Comment by rmosolgo** [comment]
Ok, tried again with #2113 and 1.8.17, could you give that version a try??

**Comment by teoljungberg** [comment]
1.8.17 works wonders, so does 1.9.x. Thanks!

**Comment by rmosolgo** [comment]
Glad to hear it, thanks for following up!
