### ISSUE TITLE
SystemStackError: stack level too deep with to_json on graphql-ruby objects

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#2214]
I reported recently in Slack about a `SystemStackError: stack level too deep` error. I discovered the cause of the issue and will document it here. This was hard to track down because of the sequencing.

**Current Behavior**

We're using `graphql-errors` since the built-in `rescue_from` only returns an error message without `extensions`. It turns out that calling `to_json` on some of the `graphql-ruby` objects that are passed in will create a `SystemStackError`:

```ruby
GraphQL::Errors.configure(GraphQLSchema) do
  rescue_from StandardError do |exception, object, arguments, context|
    # any of these will raise SystemStackError: stack level too deep
    object.to_json
    arguments.to_json
    context.to_json
  end
end
```

Our problem was that when an otherwise unhandled exception occurred, we would create a Rollbar error, which internally called `to_json` on these objects:

```ruby
Rollbar.error("Unhandled StandardError: #{exception.message}", 
              exception, 
              arguments: arguments,  # to_json gets called on this
              context: context)      # to_json gets called on this
```

When this method call failed with `SystemStackError`, Rollbars catch-all error handler captured *that* exception and reported it instead, which did not have a useful stack trace.

**Desired Behavior**

This issue is happening with `graphql-errors`, but the actual objects with the `to_json` problem are `graphql-ruby` objects. 

It turns out that `context` overflowing `to_json` is my own fault, but `object` and `arguments` are internally provided by `graphql-ruby`. `arguments` seems like it should be convertible to JSON since it's basically a hash. `object` is `Types::QueryType` and I'm not sure if there's a reasonable way to define `to_json`, but maybe it could not create a stack overflow.

```
[1] pry(#<GraphQL::Errors>)> arguments.to_json
SystemStackError: stack level too deep
from /Users/bbugh/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:171:in `dup'

[2] pry(#<GraphQL::Errors>)> arguments.to_h
=> {"id"=>"1"}
```

We're 100% on the class-based syntax, and not using any custom field definitions like #1957.

cc: @theorygeek in case this is relevant for your issue

**Comment by rmosolgo** [comment]
Thanks for the detailed bug report! I agree `arguments.to_json` should Just Work :tm:. Perhaps it should be aliased to `#to_h`.

**Comment by theorygeek** [comment]
> Perhaps it should be aliased to `#to_h`.

In Rails, `as_json` is what would be aliased to `to_h`. The `to_json` method would return a String (ie, `JSON.stringify(as_json)`)

**Comment by daemonsy** [comment]
Hi, this has been bugging us a little too. I did some investigation. 

The core issue seems to be that ActiveSupport's default behavior is to use instance variables for POROs when `#to_json` is called. 

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activesupport/lib/active_support/core_ext/object/json.rb#L57

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activesupport/lib/active_support/core_ext/object/instance_variables.rb#L15

I'd like to take this on. We can use `as_json(*)` but that's a specific method to expose on Rails. I've been flipping within these two thoughts:

1) It is ok because to expose `#as_json` calling `to_json` is a common use case for input objects, context objects etc. Since Rails is the biggest user of Ruby, go for it. 

2) We should only add the method as part of `Railtie` integration since graphql-ruby is independent of Rails.  However, the Railtie in graphql-ruby only has rake tasks, not sure if I'd like to be the first person adding more things there. 

I'll do an approach with 2) and get feedback.

**Comment by daemonsy** [comment]
Hi, a PR to start off the discussion. 

https://github.com/rmosolgo/graphql-ruby/pull/2313

**Comment by daemonsy** [comment]
Resolved by https://github.com/rmosolgo/graphql-ruby/pull/2343

**Comment by jonnymacs** [comment]
FYI - this issue persists when there is a `GraphQL::Execution::Lookahead` object in the args

**Comment by rmosolgo** [comment]
@jonnymacs, instead of leaving a comment on a closed issue, could you please open a new issue with the full error message and backtrace that you encountered? That would really help in identifying and solving the problem!

**Comment by jonnymacs** [comment]
@rmosolgo for sure! I intend to do that, just wanted to get this up for anyone that may hit this, and / or see if it's on the radar already until I have time to fill out the proper details for a new issue (which may not be for a few days here).
